### ISSUE TITLE
Backlog v0.6.0

### ISSUE THREAD

**Issue by stefan123t** [lumapu/ahoy#142]
Hier ein Vorschlag für die Liste der ToDo's für die Version 0.6.0:

* [x] Wechsel zu AsyncWebServer und ElegantOTA für Stabilität #107 
* [x] klarer Scheduler / Task manager, der ggf. den Receive Task priorisieren kann
* [x] Device Info Kommandos (Firmware Version, etc.) über das Dashboard anzeigen #145
* [x] MQTT Subscribe nur beim Reconnect #139 
* [x] Homepage aufräumen nur ein Status (aktuell drei AJAX Calls /uptime, /time, /cmdstat)
* [x] Zeitzone vom Browser ermitteln #336
* [x] Device Control Kommandos aus dem Setup ermöglichen (TurnOn, TurnOff, Restart, ActivePower Limit
* [ ] weitere Device Info Commands wie ua. 0x02 GridOnProFilePara und 0x15 GetLossRate in #145
* [ ] AlarmData & AlarmUpdate Parsen und auf eigener Seite darstellen #177 
* [x] MQTT Discovery (HomeAssistant) im Setup optional machen

------------------ SWIM LANE ---------------------------

* [x] Settings in JSON Format / settings.ini speichern (LittleFS statt EEPROM) #164
* [x] Settings exportieren / importieren (API/UI)
* [x] MI Wechselrichter unterstützen (miSystem, miInverter, miDefines, miProtokollGen2 etc.) #258
* [x] app.cpp aufräumen und in hmRadio / hmProtokollGen3 auslagern
* [x] nRF24 Interrupt Handling sinnvoll oder warum macht die nRF24 Bibliothek ständig `0x07` Statusabfragen #83 bzw. nRF24/RF24#877
* [x] Device Control Kommandos aus dem Setup ermöglichen (ReactivePower Limit, SetPowerFactor, etc.)
* [x] Zeitzone vom Browser ermitteln / manuelle Zeit / RTC #336
* [x] Styleguide(Autoformatierung) #361

---- EASY FIXES & CODE CLEANUP ----

* [ ] Debug Level im Setup änderbar -> auch Livedata Visualisierung abschalten ?

**Comment by aschiffler** [comment]
Im development branch ist nun eine einfache Anzeige für den ersten (= leider noch hardcodiert in der index.html) Umrichter. Möglich.
Mittel REST API call kann man aber auch für andere Umrichter InfoAll anfragen und diese sollten dann im MQTT auftauchen.
https://github.com/grindylow/ahoy/commit/458639b6488311efb3c894c5f916c6e4d2df7241

**Comment by DanielR92** [comment]
@stefan123t könnte man die Liste eventuell nach Dringlichkeit sortieren? =) 
Vielleicht kann ich hier und da Unterstützen. 

Edit: Wenn möglich, bei jedem Punkt ein referenz-link wo dieser Punkt hochgekommen ist? (µC, Discord, Github?)

**Comment by lumapu** [comment]
habe die Liste mal aktualisiert (entspricht dem stand im 'developemnt' Branch)

**Comment by DanielR92** [comment]
In der Swim-Lane am 3ten Punkt ist teilweise schon abgehackt oder? (fehlen würde ReactivePower Limit, SetPowerFactor; was ist mit etc. genau gemeint?)

Bitte folgenden Punkt aufnehmen: https://github.com/lumapu/ahoy/issues/336
[ ] Zeitzone vom Browser ermitteln

**Comment by DanielR92** [comment]
@stefan123t könntest du bitte folgende Punkte erweitern?
Alle Kommentare die noch offen sind in diesem PR zu bearbeiten und in das Styleguide(Autoformatierung) einfließen zu lassen?
https://github.com/lumapu/ahoy/pull/361

Danke

**Comment by stefan123t** [comment]
@DanielR92 was soll ich hier machen:
Soll ich die bereits geschlossenen Punkte aus dem ersten Post nehmen 
oder wollen wir ein neues Backlog Issue anlegen ?

**Comment by DanielR92** [comment]
Hi Stefan, 
sorry hab erst jetzt gesehen das du darauf geantwortet hast.

Ein neues Issue müssen wir nicht aufmachen dafür. Sondern können dieses Issue als Backlog zweck entfremden. 

Die oberen Punkte die Abgeschlossen sind, kann man gern entfernen und dafür neue Punkte ergänzen.
Beispielsweise auch das Thema mit NRF aus diesem Issue https://github.com/lumapu/ahoy/issues/83#issuecomment-1306231933 das mit diesem Issue vom NRF24 zusammenhängt: https://github.com/nRF24/RF24/issues/877

Danke =)

**Comment by stefan123t** [comment]
@DanielR92 Du solltest das mittels Edit mE auch ändern können aber ich habe das mal soweit nachgetragen und abgehakt. Ist glaube gar nicht mehr so viel offen ... oder ?

**Comment by lumapu** [comment]
Habe bei Settings Import den Haken wieder entfernt, da dieser Punkt noch offen ist
